{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host | default "" | quote }}
      http:
        paths:
          - path: {{ (index (index .Values.ingress.hosts 0).paths 0).path | default "/" }}
            pathType: {{ (index (index .Values.ingress.hosts 0).paths 0).pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.port | default 80 }}
{{- end }}
